# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "LiveSafe Engineering Blog"
description: "Bits and Bytes from the LiveSafe Engineering Team"

email: contact@livesafemobile.com

nav_logo: "/assets/images/logos/ls_engineering_horizontal_white.svg"
#blog logo
logo: "/assets/images/logos/ls_logo.svg"
# blog cover
# cover: "/assets/images/tech_pod.png"
cover: "/assets/images/heroes.png"

name: 'LiveSafe Engineering'
author: 'LiveSafe Engineering'
author_image: "/assets/images/ls_logo.svg"

authors:
  fox:
    name: Nick Fox
    bio: iOS Dev, Design Enthusiast
    image: "/assets/images/author_images/fox.png"
    twitter: '@nickffox'
    twitter_url: 'www.twitter.com/nickffox'
    github: nicholasffox

paginate:	10

url: "engineering.livesafemobile.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@LiveSafeDev'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/livesafe
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/livesafe
    desc:	Find us on github

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
